In [ ]:
## This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [ ]:
!pip install numpy

In [ ]:
np.__version__

In [ ]:
a = np.array([1,2,3,4,5,6,7])
a

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a[0]

In [ ]:
a = np.array([1,2,3,4,5,6,7])
a

In [ ]:
a[2:5]

In [ ]:
a[:5]

In [ ]:
a[3:]

In [ ]:
a[-5]

In [ ]:
a[1:-5]

In [ ]:
a[-2:2]

In [ ]:
np.size(a)

In [ ]:
np.shape(a)

In [ ]:
a[0,0]

In [ ]:
sorted(a, reverse=True)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a[0,0]

In [ ]:
a[1,:]

In [ ]:
a[:,2]

In [ ]:
a[:,-1] = 0
a

In [ ]:
a.shape

In [ ]:
np.size(a,1)

In [ ]:
np.ndim(a)

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

In [11]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [12]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [8]:
c = np.ones((5,5))*8
c


array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [10]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
c*d

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [4]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [5]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [6]:
np.empty([5,5])

array([[0.00000000e+000, 0.00000000e+000, 6.91770628e-310,
        1.42682308e+188, 5.87530072e+228],
       [1.31043528e-306, 5.50963561e-310, 1.42682308e+188,
        7.35163882e+228, 4.23000438e+180],
       [9.54109380e+179, 1.42547396e+188, 1.16715159e+180,
        5.95125947e+228, 5.50955020e-310],
       [6.91756941e-310, 6.91756920e-310, 6.91756920e-310,
        6.91752120e-310, 6.91756955e-310],
       [6.91756959e-310, 6.91757043e-310, 6.91756959e-310,
        6.91756959e-310, 1.02765654e-321]])

In [24]:
np.round(np.random.rand()*10)

7.0

In [25]:
[np.round(np.random.rand()*10) for item in range(10)]

[1.0, 8.0, 7.0, 6.0, 0.0, 10.0, 6.0, 1.0, 6.0, 8.0]

In [26]:
np.random.randint(5)

2

In [44]:
np.random.seed(0)
[np.random.randint(5) for item in range(10)]

[4, 0, 3, 3, 3, 1, 3, 2, 4, 0]

In [45]:
np.random.rand(5,5)

array([[0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369, 0.45615033]])

In [183]:
np.round(np.random.rand(5,5))

array([[1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([10,  1,  3,  8,  3])

In [53]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([ 7, 10,  1,  6,  8])

In [60]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix


array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0.],
       ...,
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.]])

In [61]:
idx_choose = np.random.choice(1000,100, replace = False)
idx_choose

array([537, 847,  30, 289, 812,  44, 499, 938, 592, 568, 140, 497,  70,
       481, 147, 191,   0, 340, 830,  83, 432, 500, 488,  52, 843, 961,
       461, 324, 954, 349, 776, 259, 563, 818,   1, 265, 545, 888, 653,
       492, 665, 788, 464, 541, 874, 138, 182, 952, 683, 747, 899, 751,
        95, 252, 523, 732, 910, 584,  49,  91, 416, 648,  86, 196, 466,
       467, 391, 893,  85, 806, 722, 804, 799, 779, 244,  59, 388, 968,
       232, 296, 864, 778, 199, 784,  65, 245, 358, 588, 267, 376, 990,
       786, 867, 765, 529, 797, 397, 974, 746, 865])

In [62]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0., 1., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 0., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 1.],
       [1., 1.

In [218]:
ex = np.random.rand(10,5)
ex[:,-1] = np.round(ex[:,-1])
ex

array([[0.9895038 , 0.06991917, 0.05565251, 0.36267749, 1.        ],
       [0.37996765, 0.22881285, 0.97621896, 0.23355558, 1.        ],
       [0.11170954, 0.63214097, 0.14495238, 0.27870595, 0.        ],
       [0.76501687, 0.55515843, 0.18007567, 0.75489784, 1.        ],
       [0.01922626, 0.06559892, 0.09211699, 0.2495063 , 0.        ],
       [0.6774882 , 0.65032865, 0.87200318, 0.81531452, 1.        ],
       [0.58890653, 0.10663267, 0.68774854, 0.3023215 , 1.        ],
       [0.36668678, 0.13440603, 0.60530841, 0.88280542, 0.        ],
       [0.29442592, 0.26443398, 0.78227716, 0.15217931, 0.        ],
       [0.37660283, 0.7693309 , 0.43941251, 0.24890541, 0.        ]])

Ex.2

In [171]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 6, 10,  7,  9,  0],
       [ 8,  9,  0,  6,  7],
       [ 4,  5,  8,  1,  1],
       [ 8,  8,  4,  3,  6],
       [ 9,  2,  5,  7,  9]])

In [215]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 2, 1, 2, 1],
       [2, 2, 2, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 0, 2],
       [0, 2, 0, 0, 1]])

In [71]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 1), (0, 2), (1, 0), (1, 2), (3, 1), (3, 3), (4, 3)]

In [224]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([0, 2, 0, 0, 1])

Ex.3

In [73]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[0, 2, 2, 1, 0],
       [0, 2, 0, 2, 0],
       [0, 0, 0, 2, 0]])

In [87]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [90]:
np_matrix = np.delete(np_matrix, [1,2],1)
np_matrix

array([[0, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [91]:
np_matrix

array([[0, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [95]:
a = np_matrix == 1
a

array([[False,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [96]:
np_matrix[a] = 99
np_matrix

array([[ 0, 99, 99],
       [ 0, 99, 99],
       [ 0,  0, 99]])

In [149]:
rng = np.random.RandomState(0)
data_matrix = np.random.randint(2,size = (10,5))
data_matrix

array([[1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 1, 1, 0, 1]])

Ex.4

In [148]:
label_vector = np.random.choice(2,10)
label_vector

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [156]:
train_data = data_matrix[label_vector == 0]
train_data

array([[1, 0, 1, 0, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

In [157]:
test_data = data_matrix[label_vector == 1]
test_data

array([[1, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 1, 1],
       [0, 0, 1, 1, 0]])